### ISSUE TITLE
Duplication/Gui Desync Bug

### ISSUE THREAD

**Issue by Rinbadagin** [Jarada/WuufusWaygates#11]
_Steps to recreate:_
Open waygate settings with key.
Set network icon to desired block/item to duplicate.
open settings and enter set waygate name
Re-open the waygate settings without answering the chat prompt
Enter set waygate name again.
Set name to any length of text, below or above 18 chars.
Both GUIs will return simultaneously and you will be able to remove the network icon item (alongside all other icons) and place them in your inventory.

_Suggested Fix:_
Add a flag for when user is answering a chat prompt and do not let them re-open the waygate gui when this flag is set. They should either have to wait for the chat prompt to timeout or answer it or perhaps have another way out ie doing /cancel, which will return them to the GUI.

**Comment by Jarada** [comment]
Since Github auto referencing doesn't work with multiple commits, the following two commits resolve this issue: 6b8588f581e0dc8d2f8b4e4e70726902e3d8418b and 1cb5f6b6389bd25eba0b6e09c76b8809a51b4c70
