### ISSUE TITLE
[bug] Portal break tp

### ISSUE THREAD

**Issue by FurrO2** [Jarada/WuufusWaygates#17]
When a portal connected to another one is broken, it's still possible to teleport to the broken portal by entering the unbroken one.

**Current Behavior**

Two portals are linked.
When one of the portals is broken, the player should normally no longer be able to teleport to it.
However, by breaking the destination portal, it's still possible to teleport to the broken portal.
Expected Behavior
When the destination portal is broken, the teleportation link should be severed, and the player shouldn't be able to teleport to that portal anymore.

**Steps to Reproduce the Issue**

1. Create two connected portals.
2. Break one of the portals (the starting portal).
3. Enter the unbroken portal."

**Comment by Jarada** [comment]
Hi there, this bug has been tracked down and fixed. I was already closing linked gates when a network change occurred, but not when a gate was destroyed. 

[WuufusWaygates-1.4.1.4.jar.zip](https://github.com/Jarada/WuufusWaygates/files/13403608/WuufusWaygates-1.4.1.4.jar.zip)

If this works for you, I'll get a 1.4.2 version out later today. Thanks for all your help with this!

**Comment by FurrO2** [comment]
no prob ! but i have 2 more little bugs :)
