### ISSUE TITLE
After updating WG exit location w/ WGConstructor existing routes do not get updated

### ISSUE THREAD

**Issue by aikomastboom** [Jarada/WuufusWaygates#23]
It seems that incoming connections to a gate do not get refreshed with the new exit location (until server restart.. as it looks like the json is updated correctly)

Steps to reproduce:
- create portal
- use WG constructor from the frontside to activate
- link the gate to another one.
- from a third create link back to the first
- going into the third brings to back to the front of the first gate (as expected)
- now use WG constructor from backside to re-activate
- link to the second
- go thru the third... and behold you end up at the frontside of the first.
- expected result: you end up at the newly appointed backside exit.

**Comment by Jarada** [comment]
Hey Aiko, thanks for this. I've been away for a bit but I'm back now and hopefully going to be a little less busy than the last couple months, so will look through this issue.
