### ISSUE TITLE
Mounted player takes suffocation damage if source portal is three blocks tall

### ISSUE THREAD

**Issue by kccricket** [Jarada/WuufusWaygates#5]
Paper MC build 344
WuufusWaygates 1.2.1
(no other plugins enabled)

If a player is mounted when they enter an active waygate that is three blocks tall, the player takes one tick of suffocation damage.

I would expect the player to pass without taking damage, since three blocks is normally sufficient vertical space for a mounted player to pass without suffocating.

**Comment by kccricket** [comment]
The height of the destination waygate doesn't seem to matter, though of course I didn't try a 2 block tall waygate. That'd be dumb if you're on a horse.

**Comment by Jarada** [comment]
Hi, are you able to test if this occurs on a three block waygate that isn't active? Are you able to pass through without suffocation? 

If it's possible then it's the teleportation aspect that's causing the issue, and perhaps I can prevent suffocation damage during the teleportation process. If not, there's not much I can do other than to suggest making your Waygates bigger.

**Comment by kccricket** [comment]
Yes, I tested a player can pass through 3x2 spaces without suffocation, including inactive waygates. 2x2 causes suffocation.
