### ISSUE TITLE
Incompatible with Worldguard

### ISSUE THREAD

**Issue by Dthen** [Jarada/WuufusWaygates#7]
Both plugins use the same command, `/wg`, and the same permissions.

![image](https://user-images.githubusercontent.com/65791582/104162972-7e860900-53ed-11eb-9ebf-54fad453ea43.png)

**Comment by Jarada** [comment]
For commands, I can make aliases such as `/wayg` and `/waygates`
For permissions, I can make `wg.all` which would be identical to setting `wg.*`, so it doesn't clash with World Guard.

Would this work for you?

**Comment by Jarada** [comment]
Hi, question is still open. Please do reopen the issue if there are other resolutions you'd like. Thanks!

**Comment by Dthen** [comment]
That should do it, actually, thank you veyr much!
