### ISSUE TITLE
Disruption of Nether Gate

### ISSUE THREAD

**Issue by drakmirv** [Jarada/WuufusWaygates#9]
I built a Wuufus Waygate near my nether gate.  When it is active, the nether gate stops working properly (entering the nether gate causes the swirly graphics, but no warp happens).  Breaking the Wuufus Waygate allows the nether gate to function again.  

Disabling the plugin allows the nether gate to function properly as well.

**Comment by Jarada** [comment]
This will be fixed in a future release. 

In the meantime, please ensure your two gates are at least three blocks away from each other to ensure successful functioning of both.

**Comment by drakmirv** [comment]
Understood, thanks!
